kind: Secret
apiVersion: v1
metadata:
  name: chat-app-secret
  namespace: chat-app
data:
  JWT_SECRET: ZTk0MmY5YjZlZjllNjk2ZTJiMGYxNjAxMWEwNTAzNjI=
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ28xMjM=
  MONGODB_URI: bW9uZ29kYjovL21vbmdvYWRtaW46bW9uZ28xMjNAbW9uZ29kYi5jaGF0LWFwcC5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9kYm5hbWU/YXV0aFNvdXJjZT1hZG1pbg==